import { Course } from './types';

export const MOCK_COURSES: Course[] = [
  {
    id: 'c1',
    title: 'Complete React Mastery 2024',
    instructor: 'Sarah Drasner',
    price: 89.99,
    rating: 4.8,
    reviews: 1240,
    image: 'https://picsum.photos/seed/react/800/600',
    category: 'Development',
    description: 'Master modern React including Hooks, Context, Redux, and Next.js.',
    totalLessons: 42,
  },
  {
    id: 'c2',
    title: 'UI/UX Design Fundamentals',
    instructor: 'Gary Simon',
    price: 69.99,
    rating: 4.7,
    reviews: 850,
    image: 'https://picsum.photos/seed/uiux/800/600',
    category: 'Design',
    description: 'Learn color theory, typography, and how to design beautiful interfaces.',
    totalLessons: 28,
  },
  {
    id: 'c3',
    title: 'Python for Data Science',
    instructor: 'Andrew Ng',
    price: 94.99,
    rating: 4.9,
    reviews: 2100,
    image: 'https://picsum.photos/seed/python/800/600',
    category: 'Development',
    description: 'Analyze data and build machine learning models using Python.',
    totalLessons: 55,
  },
  {
    id: 'c4',
    title: 'Digital Marketing Strategy',
    instructor: 'Seth Godin',
    price: 49.99,
    rating: 4.5,
    reviews: 430,
    image: 'https://picsum.photos/seed/marketing/800/600',
    category: 'Marketing',
    description: 'Grow your business with SEO, content marketing, and social media.',
    totalLessons: 18,
  },
  {
    id: 'c5',
    title: 'Advanced JavaScript Patterns',
    instructor: 'Kyle Simpson',
    price: 79.99,
    rating: 4.8,
    reviews: 900,
    image: 'https://picsum.photos/seed/js/800/600',
    category: 'Development',
    description: 'Deep dive into closures, prototypes, and asynchronous programming.',
    totalLessons: 35,
  },
  {
    id: 'c6',
    title: 'Business Leadership 101',
    instructor: 'Simon Sinek',
    price: 59.99,
    rating: 4.6,
    reviews: 600,
    image: 'https://picsum.photos/seed/business/800/600',
    category: 'Business',
    description: 'Inspire your team and lead with purpose.',
    totalLessons: 20,
  },
];

export const INITIAL_USER = {
  name: 'Alex Johnson',
  email: 'alex@learnflow.com',
  avatar: 'https://picsum.photos/seed/user/200/200',
};